name: Sync to Hugging Face hub For Node backend

on:
  push:
    branches: [version2]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Checkout version1 branch
        run: git checkout version1

      - name: Push to Hugging Face main branch
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote add hf https://ImashaNawodi:$HF_TOKEN@huggingface.co/spaces/ImashaNawodi/NodeBackendVersion2
          git push hf version2:main --force
